# Generated by Django 5.2.5 on 2025-08-30 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSFDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf_number', models.CharField(max_length=50, unique=True, verbose_name='NSSF Number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Status')),
                ('membership_card', models.FileField(blank=True, null=True, upload_to='nssf_cards/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Membership Card')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nssf_details', to='attachments.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_nssf_details', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'NSSF Detail',
                'verbose_name_plural': 'NSSF Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NSSFReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Return Month')),
                ('submitted_on', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('return_file', models.FileField(upload_to='nssf_returns/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'xls', 'csv'])], verbose_name='Return File')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processing Status')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Return Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nssf_returns', to='attachments.company')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'NSSF Return',
                'verbose_name_plural': 'NSSF Returns',
                'ordering': ['-submitted_on'],
                'unique_together': {('company', 'month')},
            },
        ),
    ]
